name: talent_camp_archive_script
description: Script til at opdatere kursusarkivet på GitHub.
version: 1.0.0
publish_to: 'none' # Forhindrer at du ved en fejl uploader det til pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0